/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CloudUser } from '../models';
/**
 * CloudUserApi - axios parameter creator
 * @export
 */
export const CloudUserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Logout user
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudUserControllerLogout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/cloud/me/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return user general info with accounts list
         * @summary 
         * @param {string} [source] 
         * @param {string} [medium] 
         * @param {string} [campaign] 
         * @param {string} [amp] 
         * @param {string} [_package] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudUserControllerMe: async (source?: string, medium?: string, campaign?: string, amp?: string, _package?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/cloud/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (source !== undefined) {
                localVarQueryParameter['source'] = source;
            }

            if (medium !== undefined) {
                localVarQueryParameter['medium'] = medium;
            }

            if (campaign !== undefined) {
                localVarQueryParameter['campaign'] = campaign;
            }

            if (amp !== undefined) {
                localVarQueryParameter['amp'] = amp;
            }

            if (_package !== undefined) {
                localVarQueryParameter['package'] = _package;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Activate user account
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudUserControllerSetCurrentAccount: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cloudUserControllerSetCurrentAccount', 'id', id)
            const localVarPath = `/api/cloud/me/accounts/{id}/current`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CloudUserApi - functional programming interface
 * @export
 */
export const CloudUserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CloudUserApiAxiosParamCreator(configuration)
    return {
        /**
         * Logout user
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudUserControllerLogout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudUserControllerLogout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudUserApi.cloudUserControllerLogout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return user general info with accounts list
         * @summary 
         * @param {string} [source] 
         * @param {string} [medium] 
         * @param {string} [campaign] 
         * @param {string} [amp] 
         * @param {string} [_package] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudUserControllerMe(source?: string, medium?: string, campaign?: string, amp?: string, _package?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudUserControllerMe(source, medium, campaign, amp, _package, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudUserApi.cloudUserControllerMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Activate user account
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudUserControllerSetCurrentAccount(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudUserControllerSetCurrentAccount(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudUserApi.cloudUserControllerSetCurrentAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CloudUserApi - factory interface
 * @export
 */
export const CloudUserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CloudUserApiFp(configuration)
    return {
        /**
         * Logout user
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudUserControllerLogout(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudUserControllerLogout(options).then((request) => request(axios, basePath));
        },
        /**
         * Return user general info with accounts list
         * @summary 
         * @param {string} [source] 
         * @param {string} [medium] 
         * @param {string} [campaign] 
         * @param {string} [amp] 
         * @param {string} [_package] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudUserControllerMe(source?: string, medium?: string, campaign?: string, amp?: string, _package?: string, options?: RawAxiosRequestConfig): AxiosPromise<CloudUser> {
            return localVarFp.cloudUserControllerMe(source, medium, campaign, amp, _package, options).then((request) => request(axios, basePath));
        },
        /**
         * Activate user account
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudUserControllerSetCurrentAccount(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CloudUser> {
            return localVarFp.cloudUserControllerSetCurrentAccount(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CloudUserApi - object-oriented interface
 * @export
 * @class CloudUserApi
 * @extends {BaseAPI}
 */
export class CloudUserApi extends BaseAPI {
    /**
     * Logout user
     * @summary 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CloudUserApi
     */
    public cloudUserControllerLogout(options?: RawAxiosRequestConfig) {
        return CloudUserApiFp(this.configuration).cloudUserControllerLogout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return user general info with accounts list
     * @summary 
     * @param {string} [source] 
     * @param {string} [medium] 
     * @param {string} [campaign] 
     * @param {string} [amp] 
     * @param {string} [_package] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CloudUserApi
     */
    public cloudUserControllerMe(source?: string, medium?: string, campaign?: string, amp?: string, _package?: string, options?: RawAxiosRequestConfig) {
        return CloudUserApiFp(this.configuration).cloudUserControllerMe(source, medium, campaign, amp, _package, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Activate user account
     * @summary 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CloudUserApi
     */
    public cloudUserControllerSetCurrentAccount(id: string, options?: RawAxiosRequestConfig) {
        return CloudUserApiFp(this.configuration).cloudUserControllerSetCurrentAccount(id, options).then((request) => request(this.axios, this.basePath));
    }
}

