/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PublishDto } from '../models';
// @ts-ignore
import type { PublishResponse } from '../models';
/**
 * PubSubApi - axios parameter creator
 * @export
 */
export const PubSubApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Publish message to a channel
         * @summary 
         * @param {string} dbInstance 
         * @param {PublishDto} publishDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pubSubControllerPublish: async (dbInstance: string, publishDto: PublishDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbInstance' is not null or undefined
            assertParamExists('pubSubControllerPublish', 'dbInstance', dbInstance)
            // verify required parameter 'publishDto' is not null or undefined
            assertParamExists('pubSubControllerPublish', 'publishDto', publishDto)
            const localVarPath = `/api/databases/{dbInstance}/pub-sub/messages`
                .replace(`{${"dbInstance"}}`, encodeURIComponent(String(dbInstance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(publishDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PubSubApi - functional programming interface
 * @export
 */
export const PubSubApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PubSubApiAxiosParamCreator(configuration)
    return {
        /**
         * Publish message to a channel
         * @summary 
         * @param {string} dbInstance 
         * @param {PublishDto} publishDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pubSubControllerPublish(dbInstance: string, publishDto: PublishDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PublishResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pubSubControllerPublish(dbInstance, publishDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PubSubApi.pubSubControllerPublish']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PubSubApi - factory interface
 * @export
 */
export const PubSubApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PubSubApiFp(configuration)
    return {
        /**
         * Publish message to a channel
         * @summary 
         * @param {string} dbInstance 
         * @param {PublishDto} publishDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pubSubControllerPublish(dbInstance: string, publishDto: PublishDto, options?: RawAxiosRequestConfig): AxiosPromise<PublishResponse> {
            return localVarFp.pubSubControllerPublish(dbInstance, publishDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PubSubApi - object-oriented interface
 * @export
 * @class PubSubApi
 * @extends {BaseAPI}
 */
export class PubSubApi extends BaseAPI {
    /**
     * Publish message to a channel
     * @summary 
     * @param {string} dbInstance 
     * @param {PublishDto} publishDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PubSubApi
     */
    public pubSubControllerPublish(dbInstance: string, publishDto: PublishDto, options?: RawAxiosRequestConfig) {
        return PubSubApiFp(this.configuration).pubSubControllerPublish(dbInstance, publishDto, options).then((request) => request(this.axios, this.basePath));
    }
}

