/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SlowLog } from '../models';
// @ts-ignore
import type { SlowLogConfig } from '../models';
// @ts-ignore
import type { UpdateSlowLogConfigDto } from '../models';
/**
 * SlowLogsApi - axios parameter creator
 * @export
 */
export const SlowLogsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get slowlog config
         * @summary 
         * @param {string} dbInstance 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        slowLogControllerGetConfig: async (dbInstance: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbInstance' is not null or undefined
            assertParamExists('slowLogControllerGetConfig', 'dbInstance', dbInstance)
            const localVarPath = `/api/databases/{dbInstance}/slow-logs/config`
                .replace(`{${"dbInstance"}}`, encodeURIComponent(String(dbInstance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List of slow logs
         * @summary 
         * @param {string} dbInstance 
         * @param {number} [count] Specifying the number of slow logs to fetch per node.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        slowLogControllerGetSlowLogs: async (dbInstance: string, count?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbInstance' is not null or undefined
            assertParamExists('slowLogControllerGetSlowLogs', 'dbInstance', dbInstance)
            const localVarPath = `/api/databases/{dbInstance}/slow-logs`
                .replace(`{${"dbInstance"}}`, encodeURIComponent(String(dbInstance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Clear slow logs
         * @summary 
         * @param {string} dbInstance 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        slowLogControllerResetSlowLogs: async (dbInstance: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbInstance' is not null or undefined
            assertParamExists('slowLogControllerResetSlowLogs', 'dbInstance', dbInstance)
            const localVarPath = `/api/databases/{dbInstance}/slow-logs`
                .replace(`{${"dbInstance"}}`, encodeURIComponent(String(dbInstance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update slowlog config
         * @summary 
         * @param {string} dbInstance 
         * @param {UpdateSlowLogConfigDto} updateSlowLogConfigDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        slowLogControllerUpdateConfig: async (dbInstance: string, updateSlowLogConfigDto: UpdateSlowLogConfigDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbInstance' is not null or undefined
            assertParamExists('slowLogControllerUpdateConfig', 'dbInstance', dbInstance)
            // verify required parameter 'updateSlowLogConfigDto' is not null or undefined
            assertParamExists('slowLogControllerUpdateConfig', 'updateSlowLogConfigDto', updateSlowLogConfigDto)
            const localVarPath = `/api/databases/{dbInstance}/slow-logs/config`
                .replace(`{${"dbInstance"}}`, encodeURIComponent(String(dbInstance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSlowLogConfigDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SlowLogsApi - functional programming interface
 * @export
 */
export const SlowLogsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SlowLogsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get slowlog config
         * @summary 
         * @param {string} dbInstance 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async slowLogControllerGetConfig(dbInstance: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SlowLogConfig>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.slowLogControllerGetConfig(dbInstance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SlowLogsApi.slowLogControllerGetConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List of slow logs
         * @summary 
         * @param {string} dbInstance 
         * @param {number} [count] Specifying the number of slow logs to fetch per node.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async slowLogControllerGetSlowLogs(dbInstance: string, count?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SlowLog>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.slowLogControllerGetSlowLogs(dbInstance, count, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SlowLogsApi.slowLogControllerGetSlowLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Clear slow logs
         * @summary 
         * @param {string} dbInstance 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async slowLogControllerResetSlowLogs(dbInstance: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.slowLogControllerResetSlowLogs(dbInstance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SlowLogsApi.slowLogControllerResetSlowLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update slowlog config
         * @summary 
         * @param {string} dbInstance 
         * @param {UpdateSlowLogConfigDto} updateSlowLogConfigDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async slowLogControllerUpdateConfig(dbInstance: string, updateSlowLogConfigDto: UpdateSlowLogConfigDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SlowLogConfig>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.slowLogControllerUpdateConfig(dbInstance, updateSlowLogConfigDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SlowLogsApi.slowLogControllerUpdateConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SlowLogsApi - factory interface
 * @export
 */
export const SlowLogsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SlowLogsApiFp(configuration)
    return {
        /**
         * Get slowlog config
         * @summary 
         * @param {string} dbInstance 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        slowLogControllerGetConfig(dbInstance: string, options?: RawAxiosRequestConfig): AxiosPromise<SlowLogConfig> {
            return localVarFp.slowLogControllerGetConfig(dbInstance, options).then((request) => request(axios, basePath));
        },
        /**
         * List of slow logs
         * @summary 
         * @param {string} dbInstance 
         * @param {number} [count] Specifying the number of slow logs to fetch per node.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        slowLogControllerGetSlowLogs(dbInstance: string, count?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<SlowLog>> {
            return localVarFp.slowLogControllerGetSlowLogs(dbInstance, count, options).then((request) => request(axios, basePath));
        },
        /**
         * Clear slow logs
         * @summary 
         * @param {string} dbInstance 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        slowLogControllerResetSlowLogs(dbInstance: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.slowLogControllerResetSlowLogs(dbInstance, options).then((request) => request(axios, basePath));
        },
        /**
         * Update slowlog config
         * @summary 
         * @param {string} dbInstance 
         * @param {UpdateSlowLogConfigDto} updateSlowLogConfigDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        slowLogControllerUpdateConfig(dbInstance: string, updateSlowLogConfigDto: UpdateSlowLogConfigDto, options?: RawAxiosRequestConfig): AxiosPromise<SlowLogConfig> {
            return localVarFp.slowLogControllerUpdateConfig(dbInstance, updateSlowLogConfigDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SlowLogsApi - object-oriented interface
 * @export
 * @class SlowLogsApi
 * @extends {BaseAPI}
 */
export class SlowLogsApi extends BaseAPI {
    /**
     * Get slowlog config
     * @summary 
     * @param {string} dbInstance 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SlowLogsApi
     */
    public slowLogControllerGetConfig(dbInstance: string, options?: RawAxiosRequestConfig) {
        return SlowLogsApiFp(this.configuration).slowLogControllerGetConfig(dbInstance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List of slow logs
     * @summary 
     * @param {string} dbInstance 
     * @param {number} [count] Specifying the number of slow logs to fetch per node.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SlowLogsApi
     */
    public slowLogControllerGetSlowLogs(dbInstance: string, count?: number, options?: RawAxiosRequestConfig) {
        return SlowLogsApiFp(this.configuration).slowLogControllerGetSlowLogs(dbInstance, count, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Clear slow logs
     * @summary 
     * @param {string} dbInstance 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SlowLogsApi
     */
    public slowLogControllerResetSlowLogs(dbInstance: string, options?: RawAxiosRequestConfig) {
        return SlowLogsApiFp(this.configuration).slowLogControllerResetSlowLogs(dbInstance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update slowlog config
     * @summary 
     * @param {string} dbInstance 
     * @param {UpdateSlowLogConfigDto} updateSlowLogConfigDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SlowLogsApi
     */
    public slowLogControllerUpdateConfig(dbInstance: string, updateSlowLogConfigDto: UpdateSlowLogConfigDto, options?: RawAxiosRequestConfig) {
        return SlowLogsApiFp(this.configuration).slowLogControllerUpdateConfig(dbInstance, updateSlowLogConfigDto, options).then((request) => request(this.axios, this.basePath));
    }
}

