export const RECOMMENDATION_NAMES = Object.freeze({
  // todo: moved SET_PASSWORD to top [acl list].
  //  Investigate why there is no response when placed between ZSET_HASHTABLE_TO_ZIPLIST and RSA
  SET_PASSWORD: 'setPassword',
  LUA_SCRIPT: 'luaScript',
  BIG_HASHES: 'bigHashes',
  BIG_STRINGS: 'bigStrings',
  BIG_SETS: 'bigSets',
  BIG_AMOUNT_OF_CONNECTED_CLIENTS: 'bigAmountOfConnectedClients',
  USE_SMALLER_KEYS: 'useSmallerKeys',
  AVOID_LOGICAL_DATABASES: 'avoidLogicalDatabases',
  COMBINE_SMALL_STRINGS_TO_HASHES: 'combineSmallStringsToHashes',
  INCREASE_SET_MAX_INTSET_ENTRIES: 'increaseSetMaxIntsetEntries',
  HASH_HASHTABLE_TO_ZIPLIST: 'hashHashtableToZiplist',
  COMPRESS_HASH_FIELD_NAMES: 'compressHashFieldNames',
  COMPRESSION_FOR_LIST: 'compressionForList',
  ZSET_HASHTABLE_TO_ZIPLIST: 'zSetHashtableToZiplist',
  RTS: 'RTS',
  REDIS_VERSION: 'redisVersion',
  TRY_RDI: 'tryRDI',
  SEARCH_INDEXES: 'searchIndexes',
  SEARCH_JSON: 'searchJSON',
  STRING_TO_JSON: 'stringToJson',
  SEARCH_VISUALIZATION: 'searchVisualization',
  SEARCH_HASH: 'searchHash',
});

export const ONE_NODE_RECOMMENDATIONS = [
  RECOMMENDATION_NAMES.LUA_SCRIPT,
  RECOMMENDATION_NAMES.AVOID_LOGICAL_DATABASES,
  RECOMMENDATION_NAMES.REDIS_VERSION,
  RECOMMENDATION_NAMES.SET_PASSWORD,
];

export const REDIS_STACK = [
  RECOMMENDATION_NAMES.BIG_HASHES,
  RECOMMENDATION_NAMES.BIG_SETS,
  RECOMMENDATION_NAMES.RTS,
  RECOMMENDATION_NAMES.REDIS_VERSION,
  RECOMMENDATION_NAMES.SEARCH_INDEXES,
  RECOMMENDATION_NAMES.SEARCH_JSON,
  RECOMMENDATION_NAMES.STRING_TO_JSON,
];
