version: 2.1

executors:
  docker-node:
    docker:
      - image: cimg/node:20.15

jobs:
  # Placeholder job
  placeholder-job:
    executor: docker-node
    steps:
      - checkout


workflows:
  # Placeholder workflow
  placeholder:
    jobs:
      - placeholder-job:
          name: Placeholder
          filters:
            branches:
              only:
                - placeholder
