/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PushListElementsResponseKeyName } from './push-list-elements-response-key-name';

/**
 * 
 * @export
 * @interface AddStreamEntriesResponse
 */
export interface AddStreamEntriesResponse {
    /**
     * 
     * @type {PushListElementsResponseKeyName}
     * @memberof AddStreamEntriesResponse
     */
    'keyName': PushListElementsResponseKeyName;
    /**
     * Entries IDs
     * @type {Array<string>}
     * @memberof AddStreamEntriesResponse
     */
    'entries': Array<string>;
}

