/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RedisEnterpriseDatabase } from './redis-enterprise-database';

/**
 * 
 * @export
 * @interface AddRedisEnterpriseDatabaseResponse
 */
export interface AddRedisEnterpriseDatabaseResponse {
    /**
     * The unique ID of the database
     * @type {number}
     * @memberof AddRedisEnterpriseDatabaseResponse
     */
    'uid': number;
    /**
     * Add Redis Enterprise database status
     * @type {string}
     * @memberof AddRedisEnterpriseDatabaseResponse
     */
    'status': AddRedisEnterpriseDatabaseResponseStatusEnum;
    /**
     * Message
     * @type {string}
     * @memberof AddRedisEnterpriseDatabaseResponse
     */
    'message': string;
    /**
     * The database details.
     * @type {RedisEnterpriseDatabase}
     * @memberof AddRedisEnterpriseDatabaseResponse
     */
    'databaseDetails'?: RedisEnterpriseDatabase;
    /**
     * Error
     * @type {object}
     * @memberof AddRedisEnterpriseDatabaseResponse
     */
    'error'?: object;
}

export const AddRedisEnterpriseDatabaseResponseStatusEnum = {
    Success: 'success',
    Fail: 'fail'
} as const;

export type AddRedisEnterpriseDatabaseResponseStatusEnum = typeof AddRedisEnterpriseDatabaseResponseStatusEnum[keyof typeof AddRedisEnterpriseDatabaseResponseStatusEnum];


