/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AiChatMessage } from './ai-chat-message';

/**
 * 
 * @export
 * @interface AiChat
 */
export interface AiChat {
    /**
     * 
     * @type {string}
     * @memberof AiChat
     */
    'id': string;
    /**
     * 
     * @type {Array<AiChatMessage>}
     * @memberof AiChat
     */
    'messages': Array<AiChatMessage>;
}

