/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AnalysisProgress
 */
export interface AnalysisProgress {
    /**
     * Total keys in the database
     * @type {number}
     * @memberof AnalysisProgress
     */
    'total': number;
    /**
     * Total keys scanned for entire database
     * @type {number}
     * @memberof AnalysisProgress
     */
    'scanned': number;
    /**
     * Total keys processed for entire database. (Filtered keys returned by scan command)
     * @type {number}
     * @memberof AnalysisProgress
     */
    'processed': number;
}

