/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ScanFilter } from './scan-filter';

/**
 * 
 * @export
 * @interface BrowserHistory
 */
export interface BrowserHistory {
    /**
     * History id
     * @type {string}
     * @memberof BrowserHistory
     */
    'id': string;
    /**
     * Database id
     * @type {string}
     * @memberof BrowserHistory
     */
    'databaseId': string;
    /**
     * Filters for scan operation
     * @type {ScanFilter}
     * @memberof BrowserHistory
     */
    'filter': ScanFilter;
    /**
     * Mode of history
     * @type {string}
     * @memberof BrowserHistory
     */
    'mode': BrowserHistoryModeEnum;
    /**
     * History created date (ISO string)
     * @type {string}
     * @memberof BrowserHistory
     */
    'createdAt': string;
}

export const BrowserHistoryModeEnum = {
    Pattern: 'pattern',
    Redisearch: 'redisearch'
} as const;

export type BrowserHistoryModeEnum = typeof BrowserHistoryModeEnum[keyof typeof BrowserHistoryModeEnum];


