/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CloudJobInfo
 */
export interface CloudJobInfo {
    /**
     * 
     * @type {string}
     * @memberof CloudJobInfo
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CloudJobInfo
     */
    'name': CloudJobInfoNameEnum;
    /**
     * 
     * @type {string}
     * @memberof CloudJobInfo
     */
    'status': CloudJobInfoStatusEnum;
    /**
     * Children job if any
     * @type {CloudJobInfo}
     * @memberof CloudJobInfo
     */
    'child'?: CloudJobInfo;
    /**
     * Error if any
     * @type {object}
     * @memberof CloudJobInfo
     */
    'error'?: object;
    /**
     * Job result
     * @type {object}
     * @memberof CloudJobInfo
     */
    'result'?: object;
    /**
     * Job step
     * @type {string}
     * @memberof CloudJobInfo
     */
    'step'?: string;
}

export const CloudJobInfoNameEnum = {
    CreateFreeSubscriptionAndDatabase: 'CREATE_FREE_SUBSCRIPTION_AND_DATABASE',
    CreateFreeDatabase: 'CREATE_FREE_DATABASE',
    CreateFreeSubscription: 'CREATE_FREE_SUBSCRIPTION',
    ImportFreeDatabase: 'IMPORT_FREE_DATABASE',
    WaitForActiveDatabase: 'WAIT_FOR_ACTIVE_DATABASE',
    WaitForActiveSubscription: 'WAIT_FOR_ACTIVE_SUBSCRIPTION',
    WaitForTask: 'WAIT_FOR_TASK',
    Unknown: 'UNKNOWN'
} as const;

export type CloudJobInfoNameEnum = typeof CloudJobInfoNameEnum[keyof typeof CloudJobInfoNameEnum];
export const CloudJobInfoStatusEnum = {
    Initializing: 'initializing',
    Running: 'running',
    Finished: 'finished',
    Failed: 'failed'
} as const;

export type CloudJobInfoStatusEnum = typeof CloudJobInfoStatusEnum[keyof typeof CloudJobInfoStatusEnum];


