/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CloudDatabaseDetails
 */
export interface CloudDatabaseDetails {
    /**
     * Database id from the cloud
     * @type {number}
     * @memberof CloudDatabaseDetails
     */
    'cloudId': number;
    /**
     * Subscription id from the cloud
     * @type {number}
     * @memberof CloudDatabaseDetails
     */
    'subscriptionId': number;
    /**
     * Subscription type
     * @type {string}
     * @memberof CloudDatabaseDetails
     */
    'subscriptionType': CloudDatabaseDetailsSubscriptionTypeEnum;
    /**
     * Plan memory limit
     * @type {number}
     * @memberof CloudDatabaseDetails
     */
    'planMemoryLimit'?: number;
    /**
     * Memory limit units
     * @type {string}
     * @memberof CloudDatabaseDetails
     */
    'memoryLimitMeasurementUnit'?: string;
    /**
     * Is free database
     * @type {boolean}
     * @memberof CloudDatabaseDetails
     */
    'free'?: boolean;
    /**
     * Is subscription using bdb packages
     * @type {boolean}
     * @memberof CloudDatabaseDetails
     */
    'isBdbPackage'?: boolean;
}

export const CloudDatabaseDetailsSubscriptionTypeEnum = {
    Flexible: 'flexible',
    Fixed: 'fixed'
} as const;

export type CloudDatabaseDetailsSubscriptionTypeEnum = typeof CloudDatabaseDetailsSubscriptionTypeEnum[keyof typeof CloudDatabaseDetailsSubscriptionTypeEnum];


