/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CloudAccountInfo
 */
export interface CloudAccountInfo {
    /**
     * Account id
     * @type {number}
     * @memberof CloudAccountInfo
     */
    'accountId': number;
    /**
     * Account name
     * @type {string}
     * @memberof CloudAccountInfo
     */
    'accountName': string;
    /**
     * Account owner name
     * @type {string}
     * @memberof CloudAccountInfo
     */
    'ownerName': string;
    /**
     * Account owner email
     * @type {string}
     * @memberof CloudAccountInfo
     */
    'ownerEmail': string;
}

