/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CloudCapiKey
 */
export interface CloudCapiKey {
    /**
     * 
     * @type {string}
     * @memberof CloudCapiKey
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CloudCapiKey
     */
    'userId': string;
    /**
     * Autogenerated name of capi key (Redisinsight-<RI id>-<ISO date of creation>
     * @type {string}
     * @memberof CloudCapiKey
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof CloudCapiKey
     */
    'cloudAccountId': number;
    /**
     * 
     * @type {number}
     * @memberof CloudCapiKey
     */
    'cloudUserId': number;
    /**
     * 
     * @type {string}
     * @memberof CloudCapiKey
     */
    'capiKey': string;
    /**
     * 
     * @type {string}
     * @memberof CloudCapiKey
     */
    'capiSecret': string;
    /**
     * 
     * @type {boolean}
     * @memberof CloudCapiKey
     */
    'valid': boolean;
    /**
     * 
     * @type {string}
     * @memberof CloudCapiKey
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof CloudCapiKey
     */
    'lastUsed': string;
}

