/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CloudSubscriptionRegion } from './cloud-subscription-region';

/**
 * 
 * @export
 * @interface CloudSubscriptionPlanResponse
 */
export interface CloudSubscriptionPlanResponse {
    /**
     * 
     * @type {number}
     * @memberof CloudSubscriptionPlanResponse
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof CloudSubscriptionPlanResponse
     */
    'regionId': number;
    /**
     * Subscription type
     * @type {string}
     * @memberof CloudSubscriptionPlanResponse
     */
    'type': CloudSubscriptionPlanResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CloudSubscriptionPlanResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CloudSubscriptionPlanResponse
     */
    'provider': string;
    /**
     * 
     * @type {string}
     * @memberof CloudSubscriptionPlanResponse
     */
    'region'?: string;
    /**
     * 
     * @type {number}
     * @memberof CloudSubscriptionPlanResponse
     */
    'price'?: number;
    /**
     * 
     * @type {CloudSubscriptionRegion}
     * @memberof CloudSubscriptionPlanResponse
     */
    'details': CloudSubscriptionRegion;
}

export const CloudSubscriptionPlanResponseTypeEnum = {
    Flexible: 'flexible',
    Fixed: 'fixed'
} as const;

export type CloudSubscriptionPlanResponseTypeEnum = typeof CloudSubscriptionPlanResponseTypeEnum[keyof typeof CloudSubscriptionPlanResponseTypeEnum];


