/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClusterConnectionDetailsDto
 */
export interface ClusterConnectionDetailsDto {
    /**
     * The hostname of your Redis Enterprise.
     * @type {string}
     * @memberof ClusterConnectionDetailsDto
     */
    'host': string;
    /**
     * The port your Redis Enterprise cluster is available on.
     * @type {number}
     * @memberof ClusterConnectionDetailsDto
     */
    'port': number;
    /**
     * The admin e-mail/username
     * @type {string}
     * @memberof ClusterConnectionDetailsDto
     */
    'username': string;
    /**
     * The admin password
     * @type {string}
     * @memberof ClusterConnectionDetailsDto
     */
    'password': string;
}

