/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ClusterNodeDetails } from './cluster-node-details';

/**
 * 
 * @export
 * @interface ClusterDetails
 */
export interface ClusterDetails {
    /**
     * Redis version
     * @type {string}
     * @memberof ClusterDetails
     */
    'version': string;
    /**
     * Redis mode. Currently one of: standalone, cluster or sentinel
     * @type {string}
     * @memberof ClusterDetails
     */
    'mode': string;
    /**
     * Username from the connection or undefined in case when connected with default user
     * @type {string}
     * @memberof ClusterDetails
     */
    'user'?: string;
    /**
     * Maximum value uptime_in_seconds from all nodes
     * @type {number}
     * @memberof ClusterDetails
     */
    'uptimeSec': number;
    /**
     * cluster_state from CLUSTER INFO command
     * @type {string}
     * @memberof ClusterDetails
     */
    'state': string;
    /**
     * cluster_slots_assigned from CLUSTER INFO command
     * @type {number}
     * @memberof ClusterDetails
     */
    'slotsAssigned': number;
    /**
     * cluster_slots_ok from CLUSTER INFO command
     * @type {number}
     * @memberof ClusterDetails
     */
    'slotsOk': number;
    /**
     * cluster_slots_pfail from CLUSTER INFO command
     * @type {number}
     * @memberof ClusterDetails
     */
    'slotsPFail': number;
    /**
     * cluster_slots_fail from CLUSTER INFO command
     * @type {number}
     * @memberof ClusterDetails
     */
    'slotsFail': number;
    /**
     * Calculated from (16384 - cluster_slots_assigned from CLUSTER INFO command)
     * @type {number}
     * @memberof ClusterDetails
     */
    'slotsUnassigned': number;
    /**
     * cluster_stats_messages_sent from CLUSTER INFO command
     * @type {number}
     * @memberof ClusterDetails
     */
    'statsMessagesSent': number;
    /**
     * cluster_stats_messages_received from CLUSTER INFO command
     * @type {number}
     * @memberof ClusterDetails
     */
    'statsMessagesReceived': number;
    /**
     * cluster_current_epoch from CLUSTER INFO command
     * @type {number}
     * @memberof ClusterDetails
     */
    'currentEpoch': number;
    /**
     * cluster_my_epoch from CLUSTER INFO command
     * @type {number}
     * @memberof ClusterDetails
     */
    'myEpoch': number;
    /**
     * Number of shards. cluster_size from CLUSTER INFO command
     * @type {number}
     * @memberof ClusterDetails
     */
    'size': number;
    /**
     * All nodes number in the Cluster. cluster_known_nodes from CLUSTER INFO command
     * @type {number}
     * @memberof ClusterDetails
     */
    'knownNodes': number;
    /**
     * Details per each node
     * @type {Array<ClusterNodeDetails>}
     * @memberof ClusterDetails
     */
    'nodes': Array<ClusterNodeDetails>;
}

