/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommandExecutionResult } from './command-execution-result';
// May contain unused imports in some cases
// @ts-ignore
import type { ResultsSummary } from './results-summary';

/**
 * 
 * @export
 * @interface CommandExecution
 */
export interface CommandExecution {
    /**
     * Command execution id
     * @type {string}
     * @memberof CommandExecution
     */
    'id': string;
    /**
     * Database id
     * @type {string}
     * @memberof CommandExecution
     */
    'databaseId': string;
    /**
     * Redis command
     * @type {string}
     * @memberof CommandExecution
     */
    'command': string;
    /**
     * Workbench mode
     * @type {string}
     * @memberof CommandExecution
     */
    'mode'?: CommandExecutionModeEnum;
    /**
     * Workbench result mode
     * @type {string}
     * @memberof CommandExecution
     */
    'resultsMode'?: CommandExecutionResultsModeEnum;
    /**
     * Workbench executions summary
     * @type {ResultsSummary}
     * @memberof CommandExecution
     */
    'summary'?: ResultsSummary;
    /**
     * Command execution result
     * @type {Array<CommandExecutionResult>}
     * @memberof CommandExecution
     */
    'result': Array<CommandExecutionResult>;
    /**
     * Result did not stored in db
     * @type {boolean}
     * @memberof CommandExecution
     */
    'isNotStored'?: boolean;
    /**
     * Date of command execution
     * @type {string}
     * @memberof CommandExecution
     */
    'createdAt': string;
    /**
     * Workbench command execution time
     * @type {number}
     * @memberof CommandExecution
     */
    'executionTime'?: number;
    /**
     * Logical database number.
     * @type {number}
     * @memberof CommandExecution
     */
    'db'?: number;
    /**
     * Command execution type. Used to distinguish between search and workbench
     * @type {string}
     * @memberof CommandExecution
     */
    'type'?: CommandExecutionTypeEnum;
}

export const CommandExecutionModeEnum = {
    Raw: 'RAW',
    Ascii: 'ASCII'
} as const;

export type CommandExecutionModeEnum = typeof CommandExecutionModeEnum[keyof typeof CommandExecutionModeEnum];
export const CommandExecutionResultsModeEnum = {
    Default: 'DEFAULT',
    GroupMode: 'GROUP_MODE',
    Silent: 'SILENT'
} as const;

export type CommandExecutionResultsModeEnum = typeof CommandExecutionResultsModeEnum[keyof typeof CommandExecutionResultsModeEnum];
export const CommandExecutionTypeEnum = {
    Workbench: 'WORKBENCH',
    Search: 'SEARCH'
} as const;

export type CommandExecutionTypeEnum = typeof CommandExecutionTypeEnum[keyof typeof CommandExecutionTypeEnum];


