/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConsumerDto
 */
export interface ConsumerDto {
    /**
     * The consumer\'s name
     * @type {string}
     * @memberof ConsumerDto
     */
    'name': string;
    /**
     * The number of pending messages for the client, which are messages that were delivered but are yet to be acknowledged
     * @type {number}
     * @memberof ConsumerDto
     */
    'pending': number;
    /**
     * The number of milliseconds that have passed since the consumer last interacted with the server
     * @type {number}
     * @memberof ConsumerDto
     */
    'idle': number;
}

