/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateCertSshOptionsDto
 */
export interface CreateCertSshOptionsDto {
    /**
     * The hostname of SSH server
     * @type {string}
     * @memberof CreateCertSshOptionsDto
     */
    'host': string;
    /**
     * The port of SSH server
     * @type {number}
     * @memberof CreateCertSshOptionsDto
     */
    'port': number;
    /**
     * SSH username
     * @type {string}
     * @memberof CreateCertSshOptionsDto
     */
    'username'?: string;
    /**
     * The SSH private key
     * @type {string}
     * @memberof CreateCertSshOptionsDto
     */
    'privateKey'?: string;
    /**
     * The SSH passphrase
     * @type {string}
     * @memberof CreateCertSshOptionsDto
     */
    'passphrase'?: string;
}

