/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetConsumersDtoGroupName } from './get-consumers-dto-group-name';

/**
 * 
 * @export
 * @interface CreateConsumerGroupDto
 */
export interface CreateConsumerGroupDto {
    /**
     * 
     * @type {GetConsumersDtoGroupName}
     * @memberof CreateConsumerGroupDto
     */
    'name': GetConsumersDtoGroupName;
    /**
     * Id of last delivered message
     * @type {string}
     * @memberof CreateConsumerGroupDto
     */
    'lastDeliveredId': string;
}

