/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateRedisearchIndexFieldDto } from './create-redisearch-index-field-dto';

/**
 * 
 * @export
 * @interface CreateRedisearchIndexDto
 */
export interface CreateRedisearchIndexDto {
    /**
     * Index Name
     * @type {string}
     * @memberof CreateRedisearchIndexDto
     */
    'index': string;
    /**
     * Type of keys to index
     * @type {string}
     * @memberof CreateRedisearchIndexDto
     */
    'type': CreateRedisearchIndexDtoTypeEnum;
    /**
     * Keys prefixes to find keys for index
     * @type {Array<string>}
     * @memberof CreateRedisearchIndexDto
     */
    'prefixes'?: Array<string>;
    /**
     * Fields to index
     * @type {Array<CreateRedisearchIndexFieldDto>}
     * @memberof CreateRedisearchIndexDto
     */
    'fields': Array<CreateRedisearchIndexFieldDto>;
}

export const CreateRedisearchIndexDtoTypeEnum = {
    Hash: 'hash',
    Json: 'json'
} as const;

export type CreateRedisearchIndexDtoTypeEnum = typeof CreateRedisearchIndexDtoTypeEnum[keyof typeof CreateRedisearchIndexDtoTypeEnum];


