/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateRedisearchIndexFieldDtoName } from './create-redisearch-index-field-dto-name';

/**
 * 
 * @export
 * @interface CreateRedisearchIndexFieldDto
 */
export interface CreateRedisearchIndexFieldDto {
    /**
     * 
     * @type {CreateRedisearchIndexFieldDtoName}
     * @memberof CreateRedisearchIndexFieldDto
     */
    'name': CreateRedisearchIndexFieldDtoName;
    /**
     * Type of how data must be indexed
     * @type {string}
     * @memberof CreateRedisearchIndexFieldDto
     */
    'type': CreateRedisearchIndexFieldDtoTypeEnum;
}

export const CreateRedisearchIndexFieldDtoTypeEnum = {
    Text: 'text',
    Tag: 'tag',
    Numeric: 'numeric',
    Geo: 'geo',
    Geoshape: 'geoshape',
    Vector: 'vector'
} as const;

export type CreateRedisearchIndexFieldDtoTypeEnum = typeof CreateRedisearchIndexFieldDtoTypeEnum[keyof typeof CreateRedisearchIndexFieldDtoTypeEnum];


