/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateBasicSshOptionsDto } from './create-basic-ssh-options-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CreateCertSshOptionsDto } from './create-cert-ssh-options-dto';

/**
 * @type CreateDatabaseDtoSshOptions
 * SSH Options
 * @export
 */
export type CreateDatabaseDtoSshOptions = CreateBasicSshOptionsDto | CreateCertSshOptionsDto;


