/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ScanFilter } from './scan-filter';

/**
 * 
 * @export
 * @interface CreateDatabaseAnalysisDto
 */
export interface CreateDatabaseAnalysisDto {
    /**
     * Namespace delimiter
     * @type {string}
     * @memberof CreateDatabaseAnalysisDto
     */
    'delimiter': string;
    /**
     * Filters for scan operation
     * @type {ScanFilter}
     * @memberof CreateDatabaseAnalysisDto
     */
    'filter': ScanFilter;
}

