/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateCommandExecutionsDto
 */
export interface CreateCommandExecutionsDto {
    /**
     * Workbench mode
     * @type {string}
     * @memberof CreateCommandExecutionsDto
     */
    'mode'?: CreateCommandExecutionsDtoModeEnum;
    /**
     * Workbench result mode
     * @type {string}
     * @memberof CreateCommandExecutionsDto
     */
    'resultsMode'?: CreateCommandExecutionsDtoResultsModeEnum;
    /**
     * Command execution type. Used to distinguish between search and workbench
     * @type {string}
     * @memberof CreateCommandExecutionsDto
     */
    'type'?: CreateCommandExecutionsDtoTypeEnum;
    /**
     * Redis commands
     * @type {Array<string>}
     * @memberof CreateCommandExecutionsDto
     */
    'commands': Array<string>;
}

export const CreateCommandExecutionsDtoModeEnum = {
    Raw: 'RAW',
    Ascii: 'ASCII'
} as const;

export type CreateCommandExecutionsDtoModeEnum = typeof CreateCommandExecutionsDtoModeEnum[keyof typeof CreateCommandExecutionsDtoModeEnum];
export const CreateCommandExecutionsDtoResultsModeEnum = {
    Default: 'DEFAULT',
    GroupMode: 'GROUP_MODE',
    Silent: 'SILENT'
} as const;

export type CreateCommandExecutionsDtoResultsModeEnum = typeof CreateCommandExecutionsDtoResultsModeEnum[keyof typeof CreateCommandExecutionsDtoResultsModeEnum];
export const CreateCommandExecutionsDtoTypeEnum = {
    Workbench: 'WORKBENCH',
    Search: 'SEARCH'
} as const;

export type CreateCommandExecutionsDtoTypeEnum = typeof CreateCommandExecutionsDtoTypeEnum[keyof typeof CreateCommandExecutionsDtoTypeEnum];


