/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateListWithExpireDtoKeyName } from './create-list-with-expire-dto-key-name';

/**
 * 
 * @export
 * @interface CreateRejsonRlWithExpireDto
 */
export interface CreateRejsonRlWithExpireDto {
    /**
     * 
     * @type {CreateListWithExpireDtoKeyName}
     * @memberof CreateRejsonRlWithExpireDto
     */
    'keyName': CreateListWithExpireDtoKeyName;
    /**
     * Valid json string
     * @type {string}
     * @memberof CreateRejsonRlWithExpireDto
     */
    'data': string;
    /**
     * Set a timeout on key in seconds. After the timeout has expired, the key will automatically be deleted.
     * @type {number}
     * @memberof CreateRejsonRlWithExpireDto
     */
    'expire'?: number;
}

