/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomTutorialManifestArgs } from './custom-tutorial-manifest-args';

/**
 * 
 * @export
 * @interface CustomTutorialManifest
 */
export interface CustomTutorialManifest {
    /**
     * 
     * @type {string}
     * @memberof CustomTutorialManifest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CustomTutorialManifest
     */
    'type': CustomTutorialManifestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CustomTutorialManifest
     */
    'label': string;
    /**
     * 
     * @type {string}
     * @memberof CustomTutorialManifest
     */
    'summary': string;
    /**
     * 
     * @type {CustomTutorialManifestArgs}
     * @memberof CustomTutorialManifest
     */
    'args'?: CustomTutorialManifestArgs;
    /**
     * 
     * @type {CustomTutorialManifest}
     * @memberof CustomTutorialManifest
     */
    'children'?: CustomTutorialManifest;
}

export const CustomTutorialManifestTypeEnum = {
    CodeButton: 'code-button',
    Group: 'group',
    InternalLink: 'internal-link'
} as const;

export type CustomTutorialManifestTypeEnum = typeof CustomTutorialManifestTypeEnum[keyof typeof CustomTutorialManifestTypeEnum];


