/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdditionalRedisModule } from './additional-redis-module';
// May contain unused imports in some cases
// @ts-ignore
import type { CaCertificate } from './ca-certificate';
// May contain unused imports in some cases
// @ts-ignore
import type { ClientCertificate } from './client-certificate';
// May contain unused imports in some cases
// @ts-ignore
import type { CloudDatabaseDetails } from './cloud-database-details';
// May contain unused imports in some cases
// @ts-ignore
import type { Endpoint } from './endpoint';
// May contain unused imports in some cases
// @ts-ignore
import type { SentinelMaster } from './sentinel-master';
// May contain unused imports in some cases
// @ts-ignore
import type { SshOptions } from './ssh-options';
// May contain unused imports in some cases
// @ts-ignore
import type { Tag } from './tag';

/**
 * 
 * @export
 * @interface Database
 */
export interface Database {
    /**
     * Database id.
     * @type {string}
     * @memberof Database
     */
    'id': string;
    /**
     * The hostname of your Redis database, for example redis.acme.com. If your Redis server is running on your local machine, you can enter either 127.0.0.1 or localhost.
     * @type {string}
     * @memberof Database
     */
    'host': string;
    /**
     * The port your Redis database is available on.
     * @type {number}
     * @memberof Database
     */
    'port': number;
    /**
     * A name for your Redis database.
     * @type {string}
     * @memberof Database
     */
    'name': string;
    /**
     * Logical database number.
     * @type {number}
     * @memberof Database
     */
    'db'?: number;
    /**
     * Database username, if your database is ACL enabled, otherwise leave this field empty.
     * @type {string}
     * @memberof Database
     */
    'username'?: string;
    /**
     * The password, if any, for your Redis database. If your database doesn’t require a password, leave this field empty.
     * @type {string}
     * @memberof Database
     */
    'password'?: string;
    /**
     * Connection timeout
     * @type {number}
     * @memberof Database
     */
    'timeout'?: number;
    /**
     * Connection Type
     * @type {string}
     * @memberof Database
     */
    'connectionType': DatabaseConnectionTypeEnum;
    /**
     * The database name from provider
     * @type {string}
     * @memberof Database
     */
    'nameFromProvider'?: string;
    /**
     * The redis database hosting provider
     * @type {string}
     * @memberof Database
     */
    'provider'?: string;
    /**
     * Time of the last connection to the database.
     * @type {string}
     * @memberof Database
     */
    'lastConnection': string;
    /**
     * Date of creation
     * @type {string}
     * @memberof Database
     */
    'createdAt': string;
    /**
     * Redis OSS Sentinel master group.
     * @type {SentinelMaster}
     * @memberof Database
     */
    'sentinelMaster'?: SentinelMaster;
    /**
     * OSS Cluster Nodes
     * @type {Array<Endpoint>}
     * @memberof Database
     */
    'nodes'?: Array<Endpoint>;
    /**
     * Loaded Redis modules.
     * @type {Array<AdditionalRedisModule>}
     * @memberof Database
     */
    'modules'?: Array<AdditionalRedisModule>;
    /**
     * Use TLS to connect.
     * @type {boolean}
     * @memberof Database
     */
    'tls'?: boolean;
    /**
     * SNI servername
     * @type {string}
     * @memberof Database
     */
    'tlsServername'?: string;
    /**
     * The certificate returned by the server needs to be verified.
     * @type {boolean}
     * @memberof Database
     */
    'verifyServerCert'?: boolean;
    /**
     * CA Certificate
     * @type {CaCertificate}
     * @memberof Database
     */
    'caCert'?: CaCertificate;
    /**
     * Client Certificate
     * @type {ClientCertificate}
     * @memberof Database
     */
    'clientCert'?: ClientCertificate;
    /**
     * A new created connection
     * @type {boolean}
     * @memberof Database
     */
    'new'?: boolean;
    /**
     * Use SSH tunnel to connect.
     * @type {boolean}
     * @memberof Database
     */
    'ssh'?: boolean;
    /**
     * SSH options
     * @type {SshOptions}
     * @memberof Database
     */
    'sshOptions'?: SshOptions;
    /**
     * Cloud details
     * @type {CloudDatabaseDetails}
     * @memberof Database
     */
    'cloudDetails'?: CloudDatabaseDetails;
    /**
     * Database compressor
     * @type {string}
     * @memberof Database
     */
    'compressor'?: DatabaseCompressorEnum;
    /**
     * Key name format
     * @type {string}
     * @memberof Database
     */
    'keyNameFormat'?: DatabaseKeyNameFormatEnum;
    /**
     * The version your Redis server
     * @type {string}
     * @memberof Database
     */
    'version'?: string;
    /**
     * Force client connection as standalone
     * @type {boolean}
     * @memberof Database
     */
    'forceStandalone'?: boolean;
    /**
     * Tags associated with the database.
     * @type {Array<Tag>}
     * @memberof Database
     */
    'tags'?: Array<Tag>;
    /**
     * Whether the database was created from a file or environment variables at startup
     * @type {boolean}
     * @memberof Database
     */
    'isPreSetup'?: boolean;
}

export const DatabaseConnectionTypeEnum = {
    Standalone: 'STANDALONE',
    Cluster: 'CLUSTER',
    Sentinel: 'SENTINEL',
    NotConnected: 'NOT CONNECTED'
} as const;

export type DatabaseConnectionTypeEnum = typeof DatabaseConnectionTypeEnum[keyof typeof DatabaseConnectionTypeEnum];
export const DatabaseCompressorEnum = {
    None: 'NONE',
    Gzip: 'GZIP',
    Zstd: 'ZSTD',
    Lz4: 'LZ4',
    Snappy: 'SNAPPY',
    Brotli: 'Brotli',
    PhpgzCompress: 'PHPGZCompress'
} as const;

export type DatabaseCompressorEnum = typeof DatabaseCompressorEnum[keyof typeof DatabaseCompressorEnum];
export const DatabaseKeyNameFormatEnum = {
    Unicode: 'Unicode',
    Hex: 'HEX'
} as const;

export type DatabaseKeyNameFormatEnum = typeof DatabaseKeyNameFormatEnum[keyof typeof DatabaseKeyNameFormatEnum];


