/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateListWithExpireDtoElementsInner } from './create-list-with-expire-dto-elements-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CreateListWithExpireDtoKeyName } from './create-list-with-expire-dto-key-name';

/**
 * 
 * @export
 * @interface DeleteMembersFromSetDto
 */
export interface DeleteMembersFromSetDto {
    /**
     * 
     * @type {CreateListWithExpireDtoKeyName}
     * @memberof DeleteMembersFromSetDto
     */
    'keyName': CreateListWithExpireDtoKeyName;
    /**
     * Key members
     * @type {Array<CreateListWithExpireDtoElementsInner>}
     * @memberof DeleteMembersFromSetDto
     */
    'members': Array<CreateListWithExpireDtoElementsInner>;
}

