/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HashFieldDto } from './hash-field-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PushListElementsResponseKeyName } from './push-list-elements-response-key-name';

/**
 * 
 * @export
 * @interface GetHashFieldsResponse
 */
export interface GetHashFieldsResponse {
    /**
     * 
     * @type {PushListElementsResponseKeyName}
     * @memberof GetHashFieldsResponse
     */
    'keyName': PushListElementsResponseKeyName;
    /**
     * The new cursor to use in the next call. If the property has value of 0, then the iteration is completed.
     * @type {number}
     * @memberof GetHashFieldsResponse
     */
    'nextCursor': number;
    /**
     * Array of members.
     * @type {Array<HashFieldDto>}
     * @memberof GetHashFieldsResponse
     */
    'fields': Array<HashFieldDto>;
    /**
     * The number of fields in the currently-selected hash.
     * @type {number}
     * @memberof GetHashFieldsResponse
     */
    'total': number;
}

