/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateListWithExpireDtoKeyName } from './create-list-with-expire-dto-key-name';

/**
 * 
 * @export
 * @interface GetZSetMembersDto
 */
export interface GetZSetMembersDto {
    /**
     * 
     * @type {CreateListWithExpireDtoKeyName}
     * @memberof GetZSetMembersDto
     */
    'keyName': CreateListWithExpireDtoKeyName;
    /**
     * Specifying the number of elements to skip.
     * @type {number}
     * @memberof GetZSetMembersDto
     */
    'offset': number;
    /**
     * Specifying the number of elements to return from starting at offset.
     * @type {number}
     * @memberof GetZSetMembersDto
     */
    'count': number;
    /**
     * Get elements sorted by score. In order to sort the members from the highest to the lowest score, use the DESC value, else ASC value
     * @type {string}
     * @memberof GetZSetMembersDto
     */
    'sortOrder': GetZSetMembersDtoSortOrderEnum;
}

export const GetZSetMembersDtoSortOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;

export type GetZSetMembersDtoSortOrderEnum = typeof GetZSetMembersDtoSortOrderEnum[keyof typeof GetZSetMembersDtoSortOrderEnum];


