/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetRejsonRlResponseDtoData } from './get-rejson-rl-response-dto-data';

/**
 * 
 * @export
 * @interface GetRejsonRlResponseDto
 */
export interface GetRejsonRlResponseDto {
    /**
     * Determines if json value was downloaded
     * @type {boolean}
     * @memberof GetRejsonRlResponseDto
     */
    'downloaded': boolean;
    /**
     * Type of data in the requested path
     * @type {string}
     * @memberof GetRejsonRlResponseDto
     */
    'type'?: string;
    /**
     * Requested path
     * @type {string}
     * @memberof GetRejsonRlResponseDto
     */
    'path'?: string;
    /**
     * 
     * @type {GetRejsonRlResponseDtoData}
     * @memberof GetRejsonRlResponseDto
     */
    'data': GetRejsonRlResponseDtoData | null;
}

