/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateListWithExpireDtoKeyName } from './create-list-with-expire-dto-key-name';

/**
 * 
 * @export
 * @interface GetStreamEntriesDto
 */
export interface GetStreamEntriesDto {
    /**
     * 
     * @type {CreateListWithExpireDtoKeyName}
     * @memberof GetStreamEntriesDto
     */
    'keyName': CreateListWithExpireDtoKeyName;
    /**
     * Specifying the start id
     * @type {string}
     * @memberof GetStreamEntriesDto
     */
    'start'?: string;
    /**
     * Specifying the end id
     * @type {string}
     * @memberof GetStreamEntriesDto
     */
    'end'?: string;
    /**
     * Specifying the number of entries to return.
     * @type {number}
     * @memberof GetStreamEntriesDto
     */
    'count'?: number;
    /**
     * Get entries sort by IDs order.
     * @type {string}
     * @memberof GetStreamEntriesDto
     */
    'sortOrder': GetStreamEntriesDtoSortOrderEnum;
}

export const GetStreamEntriesDtoSortOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;

export type GetStreamEntriesDtoSortOrderEnum = typeof GetStreamEntriesDtoSortOrderEnum[keyof typeof GetStreamEntriesDtoSortOrderEnum];


