/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HashFieldDtoField } from './hash-field-dto-field';

/**
 * 
 * @export
 * @interface HashFieldTtlDto
 */
export interface HashFieldTtlDto {
    /**
     * 
     * @type {HashFieldDtoField}
     * @memberof HashFieldTtlDto
     */
    'field': HashFieldDtoField;
    /**
     * Set a timeout on key in seconds. After the timeout has expired, the field will automatically be deleted. If the property has value of -1, then the field timeout will be removed.
     * @type {number}
     * @memberof HashFieldTtlDto
     */
    'expire': number;
}

