/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CloudDatabase } from './cloud-database';

/**
 * 
 * @export
 * @interface ImportCloudDatabaseResponse
 */
export interface ImportCloudDatabaseResponse {
    /**
     * Subscription id
     * @type {number}
     * @memberof ImportCloudDatabaseResponse
     */
    'subscriptionId': number;
    /**
     * Database id
     * @type {number}
     * @memberof ImportCloudDatabaseResponse
     */
    'databaseId': number;
    /**
     * Add Redis Cloud database status
     * @type {string}
     * @memberof ImportCloudDatabaseResponse
     */
    'status': ImportCloudDatabaseResponseStatusEnum;
    /**
     * Message
     * @type {string}
     * @memberof ImportCloudDatabaseResponse
     */
    'message': string;
    /**
     * The database details.
     * @type {CloudDatabase}
     * @memberof ImportCloudDatabaseResponse
     */
    'databaseDetails'?: CloudDatabase;
    /**
     * Error
     * @type {object}
     * @memberof ImportCloudDatabaseResponse
     */
    'error'?: object;
}

export const ImportCloudDatabaseResponseStatusEnum = {
    Success: 'success',
    Fail: 'fail'
} as const;

export type ImportCloudDatabaseResponseStatusEnum = typeof ImportCloudDatabaseResponseStatusEnum[keyof typeof ImportCloudDatabaseResponseStatusEnum];


