/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ImportDatabaseCloudJobDataDto
 */
export interface ImportDatabaseCloudJobDataDto {
    /**
     * Subscription id of database
     * @type {number}
     * @memberof ImportDatabaseCloudJobDataDto
     */
    'subscriptionId': number;
    /**
     * Database id to import
     * @type {number}
     * @memberof ImportDatabaseCloudJobDataDto
     */
    'databaseId': number;
    /**
     * Subscription region
     * @type {string}
     * @memberof ImportDatabaseCloudJobDataDto
     */
    'region': string;
    /**
     * Subscription provider
     * @type {string}
     * @memberof ImportDatabaseCloudJobDataDto
     */
    'provider': string;
}

