/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IndexAttibuteDto
 */
export interface IndexAttibuteDto {
    /**
     * Field identifier
     * @type {string}
     * @memberof IndexAttibuteDto
     */
    'identifier': string;
    /**
     * Field attribute
     * @type {string}
     * @memberof IndexAttibuteDto
     */
    'attribute': string;
    /**
     * Field type
     * @type {string}
     * @memberof IndexAttibuteDto
     */
    'type': string;
    /**
     * Field weight
     * @type {string}
     * @memberof IndexAttibuteDto
     */
    'WEIGHT': string;
    /**
     * Field can be sorted
     * @type {boolean}
     * @memberof IndexAttibuteDto
     */
    'SORTABLE': boolean;
    /**
     * Attributes can have the NOINDEX option, which means they will not be indexed. 
     * @type {boolean}
     * @memberof IndexAttibuteDto
     */
    'NOINDEX': boolean;
    /**
     * Attribute is case sensitive
     * @type {boolean}
     * @memberof IndexAttibuteDto
     */
    'CASESENSITIVE': boolean;
    /**
     * By default, for hashes (not with JSON) SORTABLE applies a normalization to the indexed value       (characters set to lowercase, removal of diacritics).
     * @type {boolean}
     * @memberof IndexAttibuteDto
     */
    'UNF': boolean;
    /**
     * Text attributes can have the NOSTEM argument that disables stemming when indexing its values.       This may be ideal for things like proper names.
     * @type {boolean}
     * @memberof IndexAttibuteDto
     */
    'NOSTEM': boolean;
    /**
     * Indicates how the text contained in the attribute is to be split into individual tags.       The default is ,. The value must be a single character.
     * @type {string}
     * @memberof IndexAttibuteDto
     */
    'SEPARATOR': string;
}

