/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IndexOptionsDto
 */
export interface IndexOptionsDto {
    /**
     * is a filter expression with the full RediSearch aggregation expression language.
     * @type {string}
     * @memberof IndexOptionsDto
     */
    'filter': string;
    /**
     * if set, indicates the default language for documents in the index. Default is English.
     * @type {string}
     * @memberof IndexOptionsDto
     */
    'default_lang': string;
}

