/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Key
 */
export interface Key {
    /**
     * Key name
     * @type {string}
     * @memberof Key
     */
    'name': string;
    /**
     * Key type
     * @type {string}
     * @memberof Key
     */
    'type': string;
    /**
     * Memory used by key in bytes
     * @type {number}
     * @memberof Key
     */
    'memory': number;
    /**
     * Number of characters, elements, etc. based on type
     * @type {number}
     * @memberof Key
     */
    'length': number;
    /**
     * Key ttl
     * @type {number}
     * @memberof Key
     */
    'ttl': number;
}

