/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationsDto
 */
export interface NotificationsDto {
    /**
     * Ordered notifications list
     * @type {Array<object>}
     * @memberof NotificationsDto
     */
    'notifications': Array<object>;
    /**
     * Number of unread notifications
     * @type {number}
     * @memberof NotificationsDto
     */
    'totalUnread': number;
}

