/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NspTypeSummary
 */
export interface NspTypeSummary {
    /**
     * Type name
     * @type {string}
     * @memberof NspTypeSummary
     */
    'type': string;
    /**
     * Total memory in bytes inside particular data type
     * @type {number}
     * @memberof NspTypeSummary
     */
    'memory': number;
    /**
     * Total keys inside particular data type
     * @type {number}
     * @memberof NspTypeSummary
     */
    'keys': number;
}

