/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RedisDatabaseStatsDto } from './redis-database-stats-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { RedisNodeInfoResponse } from './redis-node-info-response';

/**
 * 
 * @export
 * @interface RedisDatabaseInfoResponse
 */
export interface RedisDatabaseInfoResponse {
    /**
     * Redis database version
     * @type {string}
     * @memberof RedisDatabaseInfoResponse
     */
    'version': string;
    /**
     * Value is \"master\" if the instance is replica of no one, or \"slave\" if the instance is a replica of some master instance
     * @type {string}
     * @memberof RedisDatabaseInfoResponse
     */
    'role'?: RedisDatabaseInfoResponseRoleEnum;
    /**
     * Redis database info from server section
     * @type {object}
     * @memberof RedisDatabaseInfoResponse
     */
    'server'?: object;
    /**
     * Various Redis stats
     * @type {RedisDatabaseStatsDto}
     * @memberof RedisDatabaseInfoResponse
     */
    'stats'?: RedisDatabaseStatsDto;
    /**
     * The number of Redis databases
     * @type {number}
     * @memberof RedisDatabaseInfoResponse
     */
    'databases'?: number;
    /**
     * Total number of bytes allocated by Redis using
     * @type {number}
     * @memberof RedisDatabaseInfoResponse
     */
    'usedMemory'?: number;
    /**
     * Total number of keys inside Redis database
     * @type {number}
     * @memberof RedisDatabaseInfoResponse
     */
    'totalKeys'?: number;
    /**
     * Number of client connections (excluding connections from replicas)
     * @type {number}
     * @memberof RedisDatabaseInfoResponse
     */
    'connectedClients'?: number;
    /**
     * Number of seconds since Redis server start
     * @type {number}
     * @memberof RedisDatabaseInfoResponse
     */
    'uptimeInSeconds'?: number;
    /**
     * The cache hit ratio represents the efficiency of cache usage
     * @type {number}
     * @memberof RedisDatabaseInfoResponse
     */
    'hitRatio'?: number;
    /**
     * The number of the cached lua scripts
     * @type {number}
     * @memberof RedisDatabaseInfoResponse
     */
    'cashedScripts'?: number;
    /**
     * Nodes info
     * @type {Array<RedisNodeInfoResponse>}
     * @memberof RedisDatabaseInfoResponse
     */
    'nodes'?: Array<RedisNodeInfoResponse>;
}

export const RedisDatabaseInfoResponseRoleEnum = {
    Master: 'master',
    Slave: 'slave'
} as const;

export type RedisDatabaseInfoResponseRoleEnum = typeof RedisDatabaseInfoResponseRoleEnum[keyof typeof RedisDatabaseInfoResponseRoleEnum];


