/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomTutorialManifest } from './custom-tutorial-manifest';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomTutorialManifestArgs } from './custom-tutorial-manifest-args';

/**
 * 
 * @export
 * @interface RootCustomTutorialManifest
 */
export interface RootCustomTutorialManifest {
    /**
     * 
     * @type {string}
     * @memberof RootCustomTutorialManifest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof RootCustomTutorialManifest
     */
    'type': RootCustomTutorialManifestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof RootCustomTutorialManifest
     */
    'label': string;
    /**
     * 
     * @type {string}
     * @memberof RootCustomTutorialManifest
     */
    'summary': string;
    /**
     * 
     * @type {CustomTutorialManifestArgs}
     * @memberof RootCustomTutorialManifest
     */
    'args'?: CustomTutorialManifestArgs;
    /**
     * 
     * @type {CustomTutorialManifest}
     * @memberof RootCustomTutorialManifest
     */
    'children'?: CustomTutorialManifest;
    /**
     * 
     * @type {string}
     * @memberof RootCustomTutorialManifest
     */
    '_actions'?: RootCustomTutorialManifestActionsEnum;
    /**
     * 
     * @type {string}
     * @memberof RootCustomTutorialManifest
     */
    '_path'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RootCustomTutorialManifest
     */
    'keywords'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RootCustomTutorialManifest
     */
    'author'?: string;
    /**
     * 
     * @type {string}
     * @memberof RootCustomTutorialManifest
     */
    'url'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RootCustomTutorialManifest
     */
    'industry'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RootCustomTutorialManifest
     */
    'description'?: string;
}

export const RootCustomTutorialManifestTypeEnum = {
    CodeButton: 'code-button',
    Group: 'group',
    InternalLink: 'internal-link'
} as const;

export type RootCustomTutorialManifestTypeEnum = typeof RootCustomTutorialManifestTypeEnum[keyof typeof RootCustomTutorialManifestTypeEnum];
export const RootCustomTutorialManifestActionsEnum = {
    Create: 'create',
    Delete: 'delete',
    Sync: 'sync'
} as const;

export type RootCustomTutorialManifestActionsEnum = typeof RootCustomTutorialManifestActionsEnum[keyof typeof RootCustomTutorialManifestActionsEnum];


