/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateRedisearchIndexDtoIndex } from './create-redisearch-index-dto-index';

/**
 * 
 * @export
 * @interface SearchRedisearchDto
 */
export interface SearchRedisearchDto {
    /**
     * 
     * @type {CreateRedisearchIndexDtoIndex}
     * @memberof SearchRedisearchDto
     */
    'index': CreateRedisearchIndexDtoIndex;
    /**
     * Query to search inside data fields
     * @type {string}
     * @memberof SearchRedisearchDto
     */
    'query': string;
    /**
     * Limit number of results to be returned
     * @type {number}
     * @memberof SearchRedisearchDto
     */
    'limit': number;
    /**
     * Offset position to start searching
     * @type {number}
     * @memberof SearchRedisearchDto
     */
    'offset': number;
}

