/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateListWithExpireDtoKeyName } from './create-list-with-expire-dto-key-name';

/**
 * 
 * @export
 * @interface SearchZSetMembersDto
 */
export interface SearchZSetMembersDto {
    /**
     * 
     * @type {CreateListWithExpireDtoKeyName}
     * @memberof SearchZSetMembersDto
     */
    'keyName': CreateListWithExpireDtoKeyName;
    /**
     * Iteration cursor. An iteration starts when the cursor is set to 0, and terminates when the cursor returned by the server is 0.
     * @type {number}
     * @memberof SearchZSetMembersDto
     */
    'cursor': number;
    /**
     * Specifying the number of elements to return.
     * @type {number}
     * @memberof SearchZSetMembersDto
     */
    'count'?: number;
    /**
     * Iterate only elements matching a given pattern.
     * @type {string}
     * @memberof SearchZSetMembersDto
     */
    'match': string;
}

