/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SendCommandResponse
 */
export interface SendCommandResponse {
    /**
     * Redis CLI response
     * @type {string}
     * @memberof SendCommandResponse
     */
    'response': string;
    /**
     * Redis CLI command execution status
     * @type {string}
     * @memberof SendCommandResponse
     */
    'status': SendCommandResponseStatusEnum;
}

export const SendCommandResponseStatusEnum = {
    Success: 'success',
    Fail: 'fail'
} as const;

export type SendCommandResponseStatusEnum = typeof SendCommandResponseStatusEnum[keyof typeof SendCommandResponseStatusEnum];


