/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Endpoint } from './endpoint';

/**
 * 
 * @export
 * @interface SentinelMaster
 */
export interface SentinelMaster {
    /**
     * Sentinel master group name. Identifies a group of Redis instances composed of a master and one or more slaves.
     * @type {string}
     * @memberof SentinelMaster
     */
    'name': string;
    /**
     * Sentinel username, if your database is ACL enabled, otherwise leave this field empty.
     * @type {string}
     * @memberof SentinelMaster
     */
    'username'?: string;
    /**
     * The password for your Redis Sentinel master. If your master doesn’t require a password, leave this field empty.
     * @type {string}
     * @memberof SentinelMaster
     */
    'password'?: string;
    /**
     * The hostname of Sentinel master.
     * @type {string}
     * @memberof SentinelMaster
     */
    'host'?: string;
    /**
     * The port Sentinel master.
     * @type {number}
     * @memberof SentinelMaster
     */
    'port'?: number;
    /**
     * Sentinel master status
     * @type {string}
     * @memberof SentinelMaster
     */
    'status'?: SentinelMasterStatusEnum;
    /**
     * The number of slaves.
     * @type {number}
     * @memberof SentinelMaster
     */
    'numberOfSlaves'?: number;
    /**
     * Sentinel master endpoints.
     * @type {Array<Endpoint>}
     * @memberof SentinelMaster
     */
    'nodes'?: Array<Endpoint>;
}

export const SentinelMasterStatusEnum = {
    Active: 'active',
    Down: 'down'
} as const;

export type SentinelMasterStatusEnum = typeof SentinelMasterStatusEnum[keyof typeof SentinelMasterStatusEnum];


