/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateListWithExpireDtoKeyName } from './create-list-with-expire-dto-key-name';

/**
 * 
 * @export
 * @interface SetListElementDto
 */
export interface SetListElementDto {
    /**
     * 
     * @type {CreateListWithExpireDtoKeyName}
     * @memberof SetListElementDto
     */
    'keyName': CreateListWithExpireDtoKeyName;
    /**
     * List element
     * @type {string}
     * @memberof SetListElementDto
     */
    'element': string;
    /**
     * Element index
     * @type {number}
     * @memberof SetListElementDto
     */
    'index': number;
}

