/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SimpleTypeSummary
 */
export interface SimpleTypeSummary {
    /**
     * Type name
     * @type {string}
     * @memberof SimpleTypeSummary
     */
    'type': string;
    /**
     * Total inside this type of data
     * @type {number}
     * @memberof SimpleTypeSummary
     */
    'total': number;
}

