/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SlowLog
 */
export interface SlowLog {
    /**
     * Unique slowlog Id calculated by Redis
     * @type {number}
     * @memberof SlowLog
     */
    'id': number;
    /**
     * Time when command was executed
     * @type {number}
     * @memberof SlowLog
     */
    'time': number;
    /**
     * Time needed to execute this command in microseconds
     * @type {number}
     * @memberof SlowLog
     */
    'durationUs': number;
    /**
     * Command with args
     * @type {string}
     * @memberof SlowLog
     */
    'args': string;
    /**
     * Client that executed this command
     * @type {string}
     * @memberof SlowLog
     */
    'source': string;
    /**
     * Client name if defined
     * @type {string}
     * @memberof SlowLog
     */
    'client'?: string;
}

