/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SshOptionsResponse
 */
export interface SshOptionsResponse {
    /**
     * The hostname of SSH server
     * @type {string}
     * @memberof SshOptionsResponse
     */
    'host': string;
    /**
     * The port of SSH server
     * @type {number}
     * @memberof SshOptionsResponse
     */
    'port': number;
    /**
     * SSH username
     * @type {string}
     * @memberof SshOptionsResponse
     */
    'username'?: string;
    /**
     * The SSH password flag (true if password was set)
     * @type {boolean}
     * @memberof SshOptionsResponse
     */
    'password'?: boolean;
    /**
     * The SSH passphrase flag (true if password was set)
     * @type {boolean}
     * @memberof SshOptionsResponse
     */
    'passphrase'?: boolean;
    /**
     * The SSH private key
     * @type {boolean}
     * @memberof SshOptionsResponse
     */
    'privateKey'?: boolean;
}

