/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StreamEntryFieldDtoName } from './stream-entry-field-dto-name';
// May contain unused imports in some cases
// @ts-ignore
import type { StreamEntryFieldDtoValue } from './stream-entry-field-dto-value';

/**
 * 
 * @export
 * @interface StreamEntryFieldDto
 */
export interface StreamEntryFieldDto {
    /**
     * 
     * @type {StreamEntryFieldDtoName}
     * @memberof StreamEntryFieldDto
     */
    'name': StreamEntryFieldDtoName;
    /**
     * 
     * @type {StreamEntryFieldDtoValue}
     * @memberof StreamEntryFieldDto
     */
    'value': StreamEntryFieldDtoValue;
}

