/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * Tag id.
     * @type {string}
     * @memberof Tag
     */
    'id': string;
    /**
     * Key of the tag.
     * @type {string}
     * @memberof Tag
     */
    'key': string;
    /**
     * Value of the tag.
     * @type {string}
     * @memberof Tag
     */
    'value': string;
    /**
     * Creation date of the tag.
     * @type {string}
     * @memberof Tag
     */
    'createdAt': string;
    /**
     * Last update date of the tag.
     * @type {string}
     * @memberof Tag
     */
    'updatedAt': string;
}

