/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateSentinelMasterDto
 */
export interface UpdateSentinelMasterDto {
    /**
     * Sentinel username, if your database is ACL enabled, otherwise leave this field empty.
     * @type {string}
     * @memberof UpdateSentinelMasterDto
     */
    'username'?: string;
    /**
     * The password for your Redis Sentinel master. If your master doesn’t require a password, leave this field empty.
     * @type {string}
     * @memberof UpdateSentinelMasterDto
     */
    'password'?: string;
}

