/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateRdiDto
 */
export interface UpdateRdiDto {
    /**
     * A name to associate with RDI
     * @type {string}
     * @memberof UpdateRdiDto
     */
    'name'?: string;
    /**
     * RDI or API username
     * @type {string}
     * @memberof UpdateRdiDto
     */
    'username'?: string;
    /**
     * RDI or API password
     * @type {string}
     * @memberof UpdateRdiDto
     */
    'password'?: string;
}

