/* tslint:disable */
/* eslint-disable */
/**
 * Redis Insight Backend API
 * Redis Insight Backend API
 *
 * The version of the OpenAPI document: 2.70.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateSettingsDto
 */
export interface UpdateSettingsDto {
    /**
     * Application theme.
     * @type {string}
     * @memberof UpdateSettingsDto
     */
    'theme'?: string;
    /**
     * Application date format.
     * @type {string}
     * @memberof UpdateSettingsDto
     */
    'dateFormat'?: string;
    /**
     * Application timezone.
     * @type {string}
     * @memberof UpdateSettingsDto
     */
    'timezone'?: string;
    /**
     * Threshold for scan operation.
     * @type {number}
     * @memberof UpdateSettingsDto
     */
    'scanThreshold'?: number;
    /**
     * Batch for workbench pipeline.
     * @type {number}
     * @memberof UpdateSettingsDto
     */
    'batchSize'?: number;
    /**
     * Agreements
     * @type {object}
     * @memberof UpdateSettingsDto
     */
    'agreements'?: object;
    /**
     * Reason describing why analytics are enabled
     * @type {string}
     * @memberof UpdateSettingsDto
     */
    'analyticsReason'?: string;
}

