export enum SearchVisualizationCommands {
  FT_INFO = "FT.INFO",
  FT_SEARCH = "FT.SEARCH",
  FT_AGGREGATE = "FT.AGGREGATE",
  FT_PROFILE = "FT.PROFILE",
  FT_EXPLAIN = "FT.EXPLAIN",
  TS_RANGE = "TS.RANGE",
  TS_MRANGE = "TS.MRANGE",
}

export enum GraphVisualizationCommands {
  GRAPH_QUERY = "GRAPH.QUERY",
  GRAPH_RO_QUERY = "GRAPH.RO_QUERY",
  GRAPH_EXPLAIN = "GRAPH.EXPLAIN",
  GRAPH_PROFILE = "GRAPH.PROFILE",
}
