name: Enforce Branch Name Rules

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != feature/* && \
                "${{ github.head_ref }}" != bugfix/* && \
                "${{ github.head_ref }}" != ric/* ]]; then
            echo "❌ Pull requests to 'main' are only allowed from 'feature/**', 'bugfix/**', 'release/**', or 'ric/**' branches."
            exit 1
          fi
