name: Nightly jobs
on:
  schedule:
  - cron: 0 0 * * *

jobs:
  # Integration tests
  build-docker:
    uses: ./.github/workflows/pipeline-build-docker.yml
    secrets: inherit

  integration-tests-nightly:
    needs: build-docker
    uses: ./.github/workflows/tests-integration.yml
    secrets: inherit
    with:
      build: 'docker'
      report: true
      short_rte_list: false

  # E2E tests
  build-appimage:
    uses: ./.github/workflows/pipeline-build-linux.yml
    secrets: inherit
    with:
      target: 'linux:appimage:x64'

  e2e-appimage-nightly:
    uses: ./.github/workflows/tests-e2e-appimage.yml
    needs: build-appimage
    secrets: inherit
    with:
      report: true
