name: Nightly Virustotal Analyze

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: Provide a file URL for manual scanning (optional)
        required: false
        default: 'https://s3.amazonaws.com/redisinsight.download/public/latest/Redis-Insight-mac-arm64.dmg'
        type: string

env:
  VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}

jobs:
  analyze:
    name: Analyze file
    runs-on: ubuntu-latest

    steps:
      - name: Download file
        id: download_file
        run: |
          echo "Using File URL: ${{ github.event.inputs.file_url }}"
          curl -sLo downloaded_file "${{ github.event.inputs.file_url }}"
          echo "FILE_PATH=downloaded_file" >> $GITHUB_ENV

      - name: Get upload URL
        id: get_upload_url
        run: |
          # Request an upload URL for large files
          # Reference: https://docs.virustotal.com/reference/files-scan

          uploadUrl=$(curl -sq -XGET https://www.virustotal.com/api/v3/files/upload_url \
            -H "x-apikey: $VIRUSTOTAL_API_KEY" | jq -r '.data')

          if [ -z "$uploadUrl" ] || [ "$uploadUrl" == "null" ]; then
            echo 'Failed to retrieve upload URL from VirusTotal'
            exit 1
          fi

          echo "UPLOAD_URL=$uploadUrl" >> $GITHUB_ENV

      - name: Upload large file to VirusTotal
        id: upload_large_file
        run: |
          file_path="${{ env.FILE_PATH }}"
          upload_url="${{ env.UPLOAD_URL }}"
          echo "Uploading file: $file_path to VirusTotal using upload URL"

          # Upload the file to the provided upload URL
          # Reference: https://docs.virustotal.com/reference/files-upload-url

          analyzedId=$(curl -sq -XPOST "$upload_url" \
            -H "x-apikey: $VIRUSTOTAL_API_KEY" \
            --form "file=@${file_path}" | jq -r '.data.id')

          if [ "$analyzedId" == "null" ]; then
            echo 'File upload failed, something went wrong'
            exit 1
          fi

          echo "ANALYZED_ID=$analyzedId" >> $GITHUB_ENV

      - name: Check analyze status
        run: |
          echo "Virustotal Analyzed ID: ${ANALYZED_ID}"
          retryAttempts="50"
          intervalTime=30

          until [ "$retryAttempts" == "0" ]; do
            analyzeStatus=$(curl -sq -XGET https://www.virustotal.com/api/v3/analyses/${ANALYZED_ID} \
              -H "x-apikey: $VIRUSTOTAL_API_KEY" | jq -r '.data.attributes.status')

            if [ "$analyzeStatus" == "completed" ]; then
              echo "Current status: ${analyzeStatus}"
              break
            else
              echo "Current status: ${analyzeStatus}, retries left: ${retryAttempts}"
              sleep $intervalTime
              retryAttempts=$((retryAttempts - 1))
            fi
          done

          if [ "$analyzeStatus" != "completed" ]; then
            echo 'Analyze is not completed'
            exit 1
          fi

      - name: Validate analyze
        id: validate
        run: |
          analysis=$(curl -sq -XGET "https://www.virustotal.com/api/v3/analyses/${ANALYZED_ID}" \
             -H "x-apikey: $VIRUSTOTAL_API_KEY")

          analyzeStats=$(echo "$analysis" | jq -r '.data.attributes.stats')

          analyzedMalicious=$(echo "$analyzeStats" | jq '.malicious')
          analyzedSuspicious=$(echo "$analyzeStats" | jq '.suspicious')
          analyzedHarmless=$(echo "$analyzeStats" | jq '.harmless')

          echo "Results: Malicious: $analyzedMalicious, Suspicious: $analyzedSuspicious, Harmless: $analyzedHarmless"

          if [ "$analyzedMalicious" != "0" ] || [ "$analyzedSuspicious" != "0" ]; then
            echo "FAILED=true" >> $GITHUB_ENV

            echo "$analysis" | jq -r '.data.attributes.results[] | select(.result == "malicious" or .result == "suspicious")'

            # Exit with an error
            exit 1
          fi
