name: Nightly jobs
on:
  schedule:
  - cron: 0 0 * * *

jobs:
  # Integration tests
  build-docker:
    uses: ./.github/workflows/pipeline-build-docker.yml
    secrets: inherit

  integration-tests-nightly:
    needs: build-docker
    uses: ./.github/workflows/tests-integration.yml
    secrets: inherit
    with:
      build: 'docker'
      report: true
      short_rte_list: false

  e2e-docker-nightly:
    uses: ./.github/workflows/tests-e2e-docker.yml
    needs: build-docker
    secrets: inherit
    with:
      report: true

  # E2E tests
  build-appimage:
    uses: ./.github/workflows/pipeline-build-linux.yml
    secrets: inherit
    with:
      target: 'linux:appimage:x64'

  e2e-appimage-nightly:
    uses: ./.github/workflows/tests-e2e-appimage.yml
    needs: build-appimage
    secrets: inherit
    with:
      report: true

  clean-dev-s3:
    uses: ./.github/workflows/clean-s3-dev-builds.yml
    secrets: inherit
