name: Release docker images

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download Docker artifacts
      uses: actions/download-artifact@v4
      with:
        name: docker
        path: ./release

    - name: Publish docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
        DOCKER_V1_USER: ${{ secrets.DOCKER_V1_USER }}
        DOCKER_V1_REPO: ${{ secrets.DOCKER_V1_REPO }}
      run: |
        appVersion=$(jq -r '.version' redisinsight/package.json)

        docker login -u $DOCKER_USER -p $DOCKER_PASS

        ./.github/build/release-docker.sh \
        -d redisinsight \
        -r $DOCKER_REPO \
        -v $appVersion

        docker login -u $DOCKER_V1_USER -p $DOCKER_V1_PASS

        ./.github/build/release-docker.sh \
        -d redisinsight \
        -r $DOCKER_V1_REPO \
        -v $appVersion

