name: Remove artifacts
on:
  workflow_call:
    inputs:
      pattern:
        description: Glob pattern matching the artifacts
        type: string
        default: '*'

jobs:
  remove-artifacts:
    name: Remove artifacts
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v4

    - name: Merge artifacts by pattern
      id: merge-artifacts
      uses: actions/upload-artifact/merge@v4
      with:
        name: remove-artifacts
        pattern: ${{ inputs.pattern || '*'}}
        delete-merged: true

    - name: Delete merged artifact
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.deleteArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: ${{ steps.merge-artifacts.outputs.artifact-id }}
          });

