name: Tests E2E
on:
  push:
    branches:
      - 'e2e/**'
  workflow_dispatch:
  workflow_call:

env:
  E2E_CLOUD_DATABASE_USERNAME: ${{ secrets.E2E_CLOUD_DATABASE_USERNAME }}
  E2E_CLOUD_DATABASE_PASSWORD: ${{ secrets.E2E_CLOUD_DATABASE_PASSWORD }}
  E2E_CLOUD_API_ACCESS_KEY: ${{ secrets.E2E_CLOUD_API_ACCESS_KEY }}
  E2E_CLOUD_DATABASE_HOST: ${{ secrets.E2E_CLOUD_DATABASE_HOST }}
  E2E_CLOUD_DATABASE_PORT: ${{ secrets.E2E_CLOUD_DATABASE_PORT }}
  E2E_CLOUD_DATABASE_NAME: ${{ secrets.E2E_CLOUD_DATABASE_NAME }}
  E2E_CLOUD_API_SECRET_KEY: ${{ secrets.E2E_CLOUD_API_SECRET_KEY }}
  E2E_RI_ENCRYPTION_KEY: ${{ secrets.E2E_RI_ENCRYPTION_KEY }}
  RI_ENCRYPTION_KEY: ${{ secrets.RI_ENCRYPTION_KEY }}
  RI_SERVER_TLS_CERT: ${{ secrets.RI_SERVER_TLS_CERT }}
  RI_SERVER_TLS_KEY: ${{ secrets.RI_SERVER_TLS_KEY }}
  TEST_BIG_DB_DUMP: ${{ secrets.TEST_BIG_DB_DUMP }}

jobs:
  # build-docker:
  #   uses: ./.github/workflows/pipeline-build-docker.yml
  #   secrets: inherit

  e2e-tests:
    runs-on: ubuntu-latest
    # needs: build-docker
    container:
      image: docker:latest
      options: --privileged
      volumes:
        - /usr/src/app/results:/usr/src/app/results
        - /usr/src/app/report:/usr/src/app/report
    strategy:
      matrix:
        # Number of threads to run tests
        parallel: [0, 1, 2, 3]
    name: E2E tests
    steps:
    - uses: actions/checkout@v4

    # # TODO: uncomment
    # - name: Download Docker Artifacts
    #   if: ${{ !env.ACT }}
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: docker
    #     path: ./release

    # - run: mkdir release
    # - run: mv release2/docker-linux-alpine.amd64.tar release/docker-linux-alpine.amd64.tar
    # - run: ls -R ./release

    - name: Load built docker image from workspace
      run: |
        # TODO: uncomment
        # docker image load -i ./release/docker-linux-alpine.amd64.tar
        docker pull redis/redisinsight

        # TODO:
        git config --global --add safe.directory /__w/RedisInsight/RedisInsight

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3 #1 better
    #   with:
    #     detached: true

    - name: Generate short list of the test files
      run: |
        cd ./tests/e2e
        # !!! 40
        # testFiles=$(find tests/web -type f -name '*.e2e.ts' | sort | awk "NR % 4 == ${{ matrix.parallel }}")
        testFiles=$(find tests/web -type f -name '*.e2e.ts' | sort | awk "NR % 40 == ${{ matrix.parallel }}")
        cd ../../
        echo $testFiles

        # Multi-Line value
        echo "TEST_FILES<<EOF" >> $GITHUB_ENV
        echo "$testFiles" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Run tests
      run: |
        export NODE_INDEX=${{ matrix.parallel }}
        export TEST_FILES="tests/web/smoke/browser/edit-key-name.e2e.ts"

        TEST_BIG_DB_DUMP=$TEST_BIG_DB_DUMP \
        RI_SERVER_TLS_CERT="$RI_SERVER_TLS_CERT" \
        RI_SERVER_TLS_KEY="$RI_SERVER_TLS_KEY" \
        docker compose \
        -f tests/e2e/rte.docker-compose.yml \
        -f tests/e2e/docker.web.docker-compose.yml \
        up --abort-on-container-exit --force-recreate

    - name: Copy results
      if: always()
      run: |
        cp -R /usr/src/app/results/ ./results
        cp -R /usr/src/app/report/ ./report

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   if: always()
    #   with:
    #     detached: true

    - name: Test Results for ${{ matrix.parallel }}th node
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Tests Results
        path: results/results.xml
        reporter: java-junit
        fail-on-error: false

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: report-${{ matrix.parallel }}
        path: report



