name: Remove all artifacts

runs:
  using: 'composite'
  steps:
  - name: Merge artifacts by pattern
    id: merge-artifacts
    uses: actions/upload-artifact/merge@v4
    with:
      name: remove-artifacts
      pattern: '*'
      delete-merged: true

  - name: Delete merged artifact
    uses: actions/github-script@v7
    with:
      script: |
        github.rest.actions.deleteArtifact({
          owner: context.repo.owner,
          repo: context.repo.repo,
          artifact_id: ${{ steps.merge-artifacts.outputs.artifact-id }}
        });

